# Netlify configuration for UX Portfolio

[build]
  publish = "."

# Production context (main branch)
[context.production]
  environment = { NODE_ENV = "production" }

# Staging/branch deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "staging" }

# Deploy preview context  
[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

# Specific staging branch configuration
[context.staging]
  environment = { NODE_ENV = "staging" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"